// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"github.com/JustinHaTran/ImageRepo/ent/image"
	"github.com/JustinHaTran/ImageRepo/ent/imagerepo"
	"github.com/JustinHaTran/ImageRepo/ent/predicate"
	"github.com/facebook/ent/dialect/sql"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// ImageRepoQuery is the builder for querying ImageRepo entities.
type ImageRepoQuery struct {
	config
	limit      *int
	offset     *int
	order      []OrderFunc
	predicates []predicate.ImageRepo
	// eager-loading edges.
	withImages *ImageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the builder.
func (irq *ImageRepoQuery) Where(ps ...predicate.ImageRepo) *ImageRepoQuery {
	irq.predicates = append(irq.predicates, ps...)
	return irq
}

// Limit adds a limit step to the query.
func (irq *ImageRepoQuery) Limit(limit int) *ImageRepoQuery {
	irq.limit = &limit
	return irq
}

// Offset adds an offset step to the query.
func (irq *ImageRepoQuery) Offset(offset int) *ImageRepoQuery {
	irq.offset = &offset
	return irq
}

// Order adds an order step to the query.
func (irq *ImageRepoQuery) Order(o ...OrderFunc) *ImageRepoQuery {
	irq.order = append(irq.order, o...)
	return irq
}

// QueryImages chains the current query on the images edge.
func (irq *ImageRepoQuery) QueryImages() *ImageQuery {
	query := &ImageQuery{config: irq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := irq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := irq.sqlQuery()
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(imagerepo.Table, imagerepo.FieldID, selector),
			sqlgraph.To(image.Table, image.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, imagerepo.ImagesTable, imagerepo.ImagesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(irq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ImageRepo entity in the query. Returns *NotFoundError when no imagerepo was found.
func (irq *ImageRepoQuery) First(ctx context.Context) (*ImageRepo, error) {
	nodes, err := irq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{imagerepo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (irq *ImageRepoQuery) FirstX(ctx context.Context) *ImageRepo {
	node, err := irq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ImageRepo id in the query. Returns *NotFoundError when no id was found.
func (irq *ImageRepoQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = irq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{imagerepo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (irq *ImageRepoQuery) FirstIDX(ctx context.Context) int {
	id, err := irq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns the only ImageRepo entity in the query, returns an error if not exactly one entity was returned.
func (irq *ImageRepoQuery) Only(ctx context.Context) (*ImageRepo, error) {
	nodes, err := irq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{imagerepo.Label}
	default:
		return nil, &NotSingularError{imagerepo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (irq *ImageRepoQuery) OnlyX(ctx context.Context) *ImageRepo {
	node, err := irq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID returns the only ImageRepo id in the query, returns an error if not exactly one id was returned.
func (irq *ImageRepoQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = irq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = &NotSingularError{imagerepo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (irq *ImageRepoQuery) OnlyIDX(ctx context.Context) int {
	id, err := irq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ImageRepos.
func (irq *ImageRepoQuery) All(ctx context.Context) ([]*ImageRepo, error) {
	if err := irq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return irq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (irq *ImageRepoQuery) AllX(ctx context.Context) []*ImageRepo {
	nodes, err := irq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ImageRepo ids.
func (irq *ImageRepoQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := irq.Select(imagerepo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (irq *ImageRepoQuery) IDsX(ctx context.Context) []int {
	ids, err := irq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (irq *ImageRepoQuery) Count(ctx context.Context) (int, error) {
	if err := irq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return irq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (irq *ImageRepoQuery) CountX(ctx context.Context) int {
	count, err := irq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (irq *ImageRepoQuery) Exist(ctx context.Context) (bool, error) {
	if err := irq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return irq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (irq *ImageRepoQuery) ExistX(ctx context.Context) bool {
	exist, err := irq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (irq *ImageRepoQuery) Clone() *ImageRepoQuery {
	if irq == nil {
		return nil
	}
	return &ImageRepoQuery{
		config:     irq.config,
		limit:      irq.limit,
		offset:     irq.offset,
		order:      append([]OrderFunc{}, irq.order...),
		predicates: append([]predicate.ImageRepo{}, irq.predicates...),
		withImages: irq.withImages.Clone(),
		// clone intermediate query.
		sql:  irq.sql.Clone(),
		path: irq.path,
	}
}

//  WithImages tells the query-builder to eager-loads the nodes that are connected to
// the "images" edge. The optional arguments used to configure the query builder of the edge.
func (irq *ImageRepoQuery) WithImages(opts ...func(*ImageQuery)) *ImageRepoQuery {
	query := &ImageQuery{config: irq.config}
	for _, opt := range opts {
		opt(query)
	}
	irq.withImages = query
	return irq
}

// GroupBy used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ImageRepo.Query().
//		GroupBy(imagerepo.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (irq *ImageRepoQuery) GroupBy(field string, fields ...string) *ImageRepoGroupBy {
	group := &ImageRepoGroupBy{config: irq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := irq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return irq.sqlQuery(), nil
	}
	return group
}

// Select one or more fields from the given query.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.ImageRepo.Query().
//		Select(imagerepo.FieldName).
//		Scan(ctx, &v)
//
func (irq *ImageRepoQuery) Select(field string, fields ...string) *ImageRepoSelect {
	selector := &ImageRepoSelect{config: irq.config}
	selector.fields = append([]string{field}, fields...)
	selector.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := irq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return irq.sqlQuery(), nil
	}
	return selector
}

func (irq *ImageRepoQuery) prepareQuery(ctx context.Context) error {
	if irq.path != nil {
		prev, err := irq.path(ctx)
		if err != nil {
			return err
		}
		irq.sql = prev
	}
	return nil
}

func (irq *ImageRepoQuery) sqlAll(ctx context.Context) ([]*ImageRepo, error) {
	var (
		nodes       = []*ImageRepo{}
		_spec       = irq.querySpec()
		loadedTypes = [1]bool{
			irq.withImages != nil,
		}
	)
	_spec.ScanValues = func() []interface{} {
		node := &ImageRepo{config: irq.config}
		nodes = append(nodes, node)
		values := node.scanValues()
		return values
	}
	_spec.Assign = func(values ...interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(values...)
	}
	if err := sqlgraph.QueryNodes(ctx, irq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := irq.withImages; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		ids := make(map[int]*ImageRepo, len(nodes))
		for _, node := range nodes {
			ids[node.ID] = node
			fks = append(fks, node.ID)
			node.Edges.Images = []*Image{}
		}
		var (
			edgeids []int
			edges   = make(map[int][]*ImageRepo)
		)
		_spec := &sqlgraph.EdgeQuerySpec{
			Edge: &sqlgraph.EdgeSpec{
				Inverse: false,
				Table:   imagerepo.ImagesTable,
				Columns: imagerepo.ImagesPrimaryKey,
			},
			Predicate: func(s *sql.Selector) {
				s.Where(sql.InValues(imagerepo.ImagesPrimaryKey[0], fks...))
			},

			ScanValues: func() [2]interface{} {
				return [2]interface{}{&sql.NullInt64{}, &sql.NullInt64{}}
			},
			Assign: func(out, in interface{}) error {
				eout, ok := out.(*sql.NullInt64)
				if !ok || eout == nil {
					return fmt.Errorf("unexpected id value for edge-out")
				}
				ein, ok := in.(*sql.NullInt64)
				if !ok || ein == nil {
					return fmt.Errorf("unexpected id value for edge-in")
				}
				outValue := int(eout.Int64)
				inValue := int(ein.Int64)
				node, ok := ids[outValue]
				if !ok {
					return fmt.Errorf("unexpected node id in edges: %v", outValue)
				}
				edgeids = append(edgeids, inValue)
				edges[inValue] = append(edges[inValue], node)
				return nil
			},
		}
		if err := sqlgraph.QueryEdges(ctx, irq.driver, _spec); err != nil {
			return nil, fmt.Errorf(`query edges "images": %v`, err)
		}
		query.Where(image.IDIn(edgeids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := edges[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected "images" node returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Images = append(nodes[i].Edges.Images, n)
			}
		}
	}

	return nodes, nil
}

func (irq *ImageRepoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := irq.querySpec()
	return sqlgraph.CountNodes(ctx, irq.driver, _spec)
}

func (irq *ImageRepoQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := irq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %v", err)
	}
	return n > 0, nil
}

func (irq *ImageRepoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   imagerepo.Table,
			Columns: imagerepo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: imagerepo.FieldID,
			},
		},
		From:   irq.sql,
		Unique: true,
	}
	if ps := irq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := irq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := irq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := irq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector, imagerepo.ValidColumn)
			}
		}
	}
	return _spec
}

func (irq *ImageRepoQuery) sqlQuery() *sql.Selector {
	builder := sql.Dialect(irq.driver.Dialect())
	t1 := builder.Table(imagerepo.Table)
	selector := builder.Select(t1.Columns(imagerepo.Columns...)...).From(t1)
	if irq.sql != nil {
		selector = irq.sql
		selector.Select(selector.Columns(imagerepo.Columns...)...)
	}
	for _, p := range irq.predicates {
		p(selector)
	}
	for _, p := range irq.order {
		p(selector, imagerepo.ValidColumn)
	}
	if offset := irq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := irq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ImageRepoGroupBy is the builder for group-by ImageRepo entities.
type ImageRepoGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (irgb *ImageRepoGroupBy) Aggregate(fns ...AggregateFunc) *ImageRepoGroupBy {
	irgb.fns = append(irgb.fns, fns...)
	return irgb
}

// Scan applies the group-by query and scan the result into the given value.
func (irgb *ImageRepoGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := irgb.path(ctx)
	if err != nil {
		return err
	}
	irgb.sql = query
	return irgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := irgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: ImageRepoGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) StringsX(ctx context.Context) []string {
	v, err := irgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = irgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) StringX(ctx context.Context) string {
	v, err := irgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: ImageRepoGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) IntsX(ctx context.Context) []int {
	v, err := irgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = irgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) IntX(ctx context.Context) int {
	v, err := irgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: ImageRepoGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := irgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = irgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) Float64X(ctx context.Context) float64 {
	v, err := irgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(irgb.fields) > 1 {
		return nil, errors.New("ent: ImageRepoGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := irgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := irgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from group-by. It is only allowed when querying group-by with one field.
func (irgb *ImageRepoGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = irgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (irgb *ImageRepoGroupBy) BoolX(ctx context.Context) bool {
	v, err := irgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (irgb *ImageRepoGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range irgb.fields {
		if !imagerepo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := irgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := irgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (irgb *ImageRepoGroupBy) sqlQuery() *sql.Selector {
	selector := irgb.sql
	columns := make([]string, 0, len(irgb.fields)+len(irgb.fns))
	columns = append(columns, irgb.fields...)
	for _, fn := range irgb.fns {
		columns = append(columns, fn(selector, imagerepo.ValidColumn))
	}
	return selector.Select(columns...).GroupBy(irgb.fields...)
}

// ImageRepoSelect is the builder for select fields of ImageRepo entities.
type ImageRepoSelect struct {
	config
	fields []string
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Scan applies the selector query and scan the result into the given value.
func (irs *ImageRepoSelect) Scan(ctx context.Context, v interface{}) error {
	query, err := irs.path(ctx)
	if err != nil {
		return err
	}
	irs.sql = query
	return irs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (irs *ImageRepoSelect) ScanX(ctx context.Context, v interface{}) {
	if err := irs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Strings(ctx context.Context) ([]string, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: ImageRepoSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (irs *ImageRepoSelect) StringsX(ctx context.Context) []string {
	v, err := irs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = irs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (irs *ImageRepoSelect) StringX(ctx context.Context) string {
	v, err := irs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Ints(ctx context.Context) ([]int, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: ImageRepoSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (irs *ImageRepoSelect) IntsX(ctx context.Context) []int {
	v, err := irs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = irs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (irs *ImageRepoSelect) IntX(ctx context.Context) int {
	v, err := irs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: ImageRepoSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (irs *ImageRepoSelect) Float64sX(ctx context.Context) []float64 {
	v, err := irs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = irs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (irs *ImageRepoSelect) Float64X(ctx context.Context) float64 {
	v, err := irs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(irs.fields) > 1 {
		return nil, errors.New("ent: ImageRepoSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := irs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (irs *ImageRepoSelect) BoolsX(ctx context.Context) []bool {
	v, err := irs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from selector. It is only allowed when selecting one field.
func (irs *ImageRepoSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = irs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{imagerepo.Label}
	default:
		err = fmt.Errorf("ent: ImageRepoSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (irs *ImageRepoSelect) BoolX(ctx context.Context) bool {
	v, err := irs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (irs *ImageRepoSelect) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range irs.fields {
		if !imagerepo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for selection", f)}
		}
	}
	rows := &sql.Rows{}
	query, args := irs.sqlQuery().Query()
	if err := irs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (irs *ImageRepoSelect) sqlQuery() sql.Querier {
	selector := irs.sql
	selector.Select(selector.Columns(irs.fields...)...)
	return selector
}
