// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/JustinHaTran/ImageRepo/ent/image"
	"github.com/JustinHaTran/ImageRepo/ent/imagerepo"
	"github.com/facebook/ent/dialect/sql/sqlgraph"
	"github.com/facebook/ent/schema/field"
)

// ImageRepoCreate is the builder for creating a ImageRepo entity.
type ImageRepoCreate struct {
	config
	mutation *ImageRepoMutation
	hooks    []Hook
}

// SetName sets the name field.
func (irc *ImageRepoCreate) SetName(s string) *ImageRepoCreate {
	irc.mutation.SetName(s)
	return irc
}

// AddImageIDs adds the images edge to Image by ids.
func (irc *ImageRepoCreate) AddImageIDs(ids ...int) *ImageRepoCreate {
	irc.mutation.AddImageIDs(ids...)
	return irc
}

// AddImages adds the images edges to Image.
func (irc *ImageRepoCreate) AddImages(i ...*Image) *ImageRepoCreate {
	ids := make([]int, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return irc.AddImageIDs(ids...)
}

// Mutation returns the ImageRepoMutation object of the builder.
func (irc *ImageRepoCreate) Mutation() *ImageRepoMutation {
	return irc.mutation
}

// Save creates the ImageRepo in the database.
func (irc *ImageRepoCreate) Save(ctx context.Context) (*ImageRepo, error) {
	var (
		err  error
		node *ImageRepo
	)
	if len(irc.hooks) == 0 {
		if err = irc.check(); err != nil {
			return nil, err
		}
		node, err = irc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ImageRepoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = irc.check(); err != nil {
				return nil, err
			}
			irc.mutation = mutation
			node, err = irc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(irc.hooks) - 1; i >= 0; i-- {
			mut = irc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, irc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (irc *ImageRepoCreate) SaveX(ctx context.Context) *ImageRepo {
	v, err := irc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (irc *ImageRepoCreate) check() error {
	if _, ok := irc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := irc.mutation.Name(); ok {
		if err := imagerepo.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	return nil
}

func (irc *ImageRepoCreate) sqlSave(ctx context.Context) (*ImageRepo, error) {
	_node, _spec := irc.createSpec()
	if err := sqlgraph.CreateNode(ctx, irc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (irc *ImageRepoCreate) createSpec() (*ImageRepo, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageRepo{config: irc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: imagerepo.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: imagerepo.FieldID,
			},
		}
	)
	if value, ok := irc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: imagerepo.FieldName,
		})
		_node.Name = value
	}
	if nodes := irc.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   imagerepo.ImagesTable,
			Columns: imagerepo.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: image.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ImageRepoCreateBulk is the builder for creating a bulk of ImageRepo entities.
type ImageRepoCreateBulk struct {
	config
	builders []*ImageRepoCreate
}

// Save creates the ImageRepo entities in the database.
func (ircb *ImageRepoCreateBulk) Save(ctx context.Context) ([]*ImageRepo, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ircb.builders))
	nodes := make([]*ImageRepo, len(ircb.builders))
	mutators := make([]Mutator, len(ircb.builders))
	for i := range ircb.builders {
		func(i int, root context.Context) {
			builder := ircb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageRepoMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ircb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ircb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ircb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX calls Save and panics if Save returns an error.
func (ircb *ImageRepoCreateBulk) SaveX(ctx context.Context) []*ImageRepo {
	v, err := ircb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
