// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/JustinHaTran/ImageRepo/ent/imagerepo"
	"github.com/facebook/ent/dialect/sql"
)

// ImageRepo is the model entity for the ImageRepo schema.
type ImageRepo struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageRepoQuery when eager-loading is set.
	Edges ImageRepoEdges `json:"edges"`
}

// ImageRepoEdges holds the relations/edges for other nodes in the graph.
type ImageRepoEdges struct {
	// Images holds the value of the images edge.
	Images []*Image
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e ImageRepoEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[0] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageRepo) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullString{}, // name
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageRepo fields.
func (ir *ImageRepo) assignValues(values ...interface{}) error {
	if m, n := len(values), len(imagerepo.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	ir.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value.Valid {
		ir.Name = value.String
	}
	return nil
}

// QueryImages queries the images edge of the ImageRepo.
func (ir *ImageRepo) QueryImages() *ImageQuery {
	return (&ImageRepoClient{config: ir.config}).QueryImages(ir)
}

// Update returns a builder for updating this ImageRepo.
// Note that, you need to call ImageRepo.Unwrap() before calling this method, if this ImageRepo
// was returned from a transaction, and the transaction was committed or rolled back.
func (ir *ImageRepo) Update() *ImageRepoUpdateOne {
	return (&ImageRepoClient{config: ir.config}).UpdateOne(ir)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (ir *ImageRepo) Unwrap() *ImageRepo {
	tx, ok := ir.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageRepo is not a transactional entity")
	}
	ir.config.driver = tx.drv
	return ir
}

// String implements the fmt.Stringer.
func (ir *ImageRepo) String() string {
	var builder strings.Builder
	builder.WriteString("ImageRepo(")
	builder.WriteString(fmt.Sprintf("id=%v", ir.ID))
	builder.WriteString(", name=")
	builder.WriteString(ir.Name)
	builder.WriteByte(')')
	return builder.String()
}

// ImageRepos is a parsable slice of ImageRepo.
type ImageRepos []*ImageRepo

func (ir ImageRepos) config(cfg config) {
	for _i := range ir {
		ir[_i].config = cfg
	}
}
