// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/JustinHaTran/ImageRepo/ent/imagerepo"
	"github.com/JustinHaTran/ImageRepo/ent/schema"
	"github.com/JustinHaTran/ImageRepo/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	imagerepoFields := schema.ImageRepo{}.Fields()
	_ = imagerepoFields
	// imagerepoDescName is the schema descriptor for name field.
	imagerepoDescName := imagerepoFields[0].Descriptor()
	// imagerepo.NameValidator is a validator for the "name" field. It is called by the builders before save.
	imagerepo.NameValidator = imagerepoDescName.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAge is the schema descriptor for age field.
	userDescAge := userFields[0].Descriptor()
	// user.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	user.AgeValidator = userDescAge.Validators[0].(func(int) error)
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[1].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
}
