// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// ImageRepo is the predicate function for imagerepo builders.
type ImageRepo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
